[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "c3po_experiments"
version = "0.0.1"
dependencies = [
  "torch>=2.1.0",
  "transformers>=4.34.0",
  "datasets>=2.14.7",
  "accelerate>=0.23.0",
  "evaluate>=0.4.0",
  "scipy>=1.11.3",
  "rouge-score>=0.1.2",
  "matplotlib>=3.8.0",
  "seaborn>=0.13.0",
  "tqdm>=4.66.1",
  "ptflops>=0.7.1",
  "pyyaml>=6.0"
]
